providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = ["npm install --omit=dev --frozen-lockfile"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/server/server.js"

[variables]
NIXPACKS_NODE_VERSION = "20"
